baseurl: /wedding
sass:
    style: compressed
    sass_dir: _sass
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
collections:
  guests:
    output: true
    permalink: /:collection/:name            